// tarefa-unidade-1/votacao-svelte/src/components/VotingCard/VotingCard.svelte
<script>
  import VoteList from '../VoteList/VoteList.svelte';
  import Result from '../Result/Result.svelte';

  export let state = 'open';
  export let title = '';
  export let votes = [];

  let previousVotes = null;

  let currentVotes = null;

  function getVotingOptions() {
    return votes.map(item => item.option);
  }

  function onSelectVote(selectedVote) {
    currentVotes = currentVotes.map(
      (item) => (
        item.option === selectedVote
          ? { ...item, count: item.count + 1 }
          : item
      )
    )
  }

  $: {
    if (previousVotes !== votes) {
      currentVotes = votes;
      previousVotes = votes;
      console.log(votes, currentVotes, previousVotes)
    }
  }
</script>

<style lang="scss">
  @import './VotingCard.scss';
</style>

<div class="voting-card">
  {#if state === 'open'}
    <h3 class="voting-card__title">{title}</h3>
    <div class="voting-card__cabinet">
      <VoteList
        options={getVotingOptions()}
        on:vote={onSelectVote}
      />
    </div>
  {:else if state === 'closed'}
    <Result votes={currentVotes} />
  {/if}
</div>

// tarefa-unidade-1/votacao-react/src/components/VotingCard/VotingCard.jsx
import { useState } from 'react';
import PropTypes from 'prop-types';
import VoteList from '../VoteList/VoteList';
import Result from '../Result/Result';
import './VotingCard.scss';

function VotingCard(props) {
  const { title, state, votes } = props;

  const isVotingEnabled = state === 'open';
  const votingOptions = votes.map(item => item.option);

  const [currentVotes, setCurrentVotes] = useState(votes);

  const onVote = selectedVote => {
    setCurrentVotes(previousVotes => {
      return previousVotes.map(item => item.option === selectedVote
        ? { ...item, count: item.count + 1 }
        : item
      )
    })
  }

  return (
    <div className="voting-card">
      {isVotingEnabled ? (
        <>
          <h3 className="voting-card__title">{title}</h3>
          <div className="voting-card__cabinet">
            <VoteList options={votingOptions} onVote={onVote}/>
          </div>
        </>
      ) : (
        <Result votes={currentVotes} />
      )}
    </div>
  );
}

VotingCard.propTypes = {
  title: PropTypes.string,
  state: PropTypes.oneOf(['open', 'closed']),
  votes: PropTypes.arrayOf(PropTypes.shape({
    option: PropTypes.string,
    count: PropTypes.number
  }))
}

VotingCard.defaultProps = {
  title: '',
  state: 'open',
  votes: []
}

export default VotingCard;
