// tarefa-unidade-2/formulario-react/src/components/ProductList/ProductList.jsx
import PropTypes from 'prop-types';
import { useState } from 'react';
import { v4 as uuid } from 'uuid';
import './ProductList.css';
import EditableProduct from '../EditableProduct/EditableProduct';

function insertIdentifier(data) {
  return { ...data, uuid: uuid() };
}

function ProductList(props) {
  const { products } = props;
  const [currentProducts, setCurrentProducts] = useState(products.map(insertIdentifier));
  const updateProduct = productUuid => data => setCurrentProducts(
    previousProducts => previousProducts.map(product => {
      if (product.uuid === productUuid)
        return { ...product, ...data };
      return product;
    })
  )

  return (
    <div className="product-list">
      {currentProducts.map(
        product => <EditableProduct key={product.uuid} {...product} onSave={updateProduct(product.uuid)} />
      )}
    </div>
  );
}

ProductList.propTypes = {
  products: PropTypes.array
}

ProductList.defaultProps = {
  products: []
}

export default ProductList;

// tarefa-unidade-2/formulario-vue/src/components/ProductList/ProductList.vue
<template>
  <div class="product-list">
    <editable-product
      v-for="product in state.products" :key="product.uuid"
      :price="product.price"
      :imageSrc="product.imageSrc"
      :title="product.title"
      :description="product.description"
      @save="onSave(product.uuid, $event)"
    ></editable-product>
  </div>
</template>

<script>
import { v4 as uuid } from 'uuid';
import { reactive } from 'vue';
import EditableProduct from '../EditableProduct/EditableProduct.vue';
import './ProductList.css';

export default {
  name: 'product-list',
  props: {
    products: {
      type: Array,
      require: false,
      default: []
    }
  },
  components: { EditableProduct },
  setup(props) {
    const state = reactive({
      products: props.products.map(product => ({ ...product, uuid: uuid() }))
    });

    return {
      state,
      onSave: (productUUID, newData) => {
        state.products = state.products.map(product => {
          if (product.uuid === productUUID)
            return { ...product, ...newData };
          return product;
        });
      }
    }
  }
}
</script>
