// tarefa-unidade-2/formulario-vue/src/components/ProductDetails/ProductDetails.vue
<template>
  <div class="product-details">
    <div class="product-details__body">
      <div class="product-details__image-container" >
        <template v-if="!!imageSrc">
          <img
            alt="Product"
            class="product-details__image"
            :src="imageSrc"
          />
        </template>
        <template v-else>
          No image
        </template>
        <span class="product-details__price">
          {{ formattedPrice }}
        </span>
      </div>
      <h3 class="product-details__title">{{ title }}</h3>
      <h4 class="product-details__description">{{ description }}</h4>
    </div>
    <div class="product-details__footer">
      <button>Buy Now</button>
    </div>
  </div>
</template>

<script>
import { computed } from 'vue';
import './ProductDetails.css';

export default {
  name: 'product-details',
  props: [
    'imageSrc',
    'price',
    'title',
    'description'
  ],
  setup(props) {
    return {
      formattedPrice: computed(() => {
        const parsedPrice = parseFloat(props.price.toString());
        return `R$ ${parsedPrice.toFixed(2)}`;
      }),
    }
  }
}
</script>

// tarefa-unidade-2/formulario-react/src/components/ProductDetails/ProductDetails.jsx
import PropTypes from 'prop-types';

import './ProductDetails.css';

function formatPrice(price) {
  const parsedPrice = parseFloat(price.toString());
  return `R$ ${parsedPrice.toFixed(2)}`;
}

function ProductDetails(props) {
  const { price, imageSrc, title, description } = props;

  return (
    <div className="product-details">
      <div className="product-details__body">
        <div className="product-details__image-container">
          {!imageSrc ? (
            'No image'
          ) : (
            <img
              alt="Product"
              className="product-details__image"
              src={imageSrc}
            />
          )}
          <span className="product-details__price">
            {formatPrice(price)}
          </span>
        </div>
        <h3 className="product-details__title">{title}</h3>
        <h4 className="product-details__description">{description}</h4>
      </div>
      <div className="product-details__footer">
        <button>Buy Now</button>
      </div>
    </div>
  );
}

ProductDetails.propTypes = {
  price: PropTypes.number,
  imageSrc: PropTypes.string,
  title: PropTypes.string,
  description: PropTypes.string,
}

ProductDetails.defaultProps = {
  price: 0,
  imageSrc: '',
  title: '',
  description: ''
}

export default ProductDetails;
