// tarefa-unidade-1/votacao-angular/src/components/VotingCard/VotingCard.component.ts
import { Component, Input, OnChanges, SimpleChanges } from "@angular/core";
import { VoteInterface } from "../sharedInterfaces";

@Component({
  selector: 'voting-card',
  template: `<div class="voting-card">
    <ng-template [ngIf]="state === 'open'">
      <h3 class="voting-card__title">{{title}}</h3>
      <div class="voting-card__cabinet">
        <vote-list [options]="votingOptions" (onVote)="onSelectVote($event)"></vote-list>
      </div>
    </ng-template>
    <ng-template [ngIf]="state === 'closed'">
      <result [votes]="currentVotes"></result>
    </ng-template>
  </div>`,
  styleUrls: ['./VotingCard.scss'],
})
export default class VotingCardComponent implements OnChanges {
  @Input()
  state: String = 'open';

  @Input()
  title: String = '';

  @Input()
  votes: Array<VoteInterface> = [];

  ngOnChanges(changes: SimpleChanges) {
    if (changes.votes) {
      this.currentVotes = changes.votes.currentValue;
    }
  };

  public get votingOptions(): Array<String> {
    return this.votes.map(item => item.option);
  }

  public currentVotes: Array<VoteInterface> = [];

  public onSelectVote(selectedVote: String): void {
    this.currentVotes = this.currentVotes.map(
      (item) => (
        item.option === selectedVote
          ? { ...item, count: item.count + 1 }
          : item
      )
    )
  }
}

// tarefa-unidade-1/votacao-vue/src/components/VotingCard/VotingCard.vue
<template>
  <div class="voting-card">
    <template v-if="isVotingEnabled">
      <h3 class="voting-card__title">{{title}}</h3>
      <div class="voting-card__cabinet">
        <vote-list :options="votingOptions" :onVote="onVote" />
      </div>
    </template>
    <template v-else>
      <result :votes="currentVotes" />
    </template>
  </div>
</template>

<script>
import VoteList from '../VoteList/VoteList.vue';
import Result from '../Result/Result.vue';

export default {
  props: {
    title: {
      type: String,
      default: ''
    },
    state: {
      type: String,
      default: 'open'
    },
    votes: {
      type: Array,
      default: () => []
    }
  },
  data: function() {
    return {
      currentVotes: this.votes
    }
  },
  methods: {
    onVote: function(selectedOption) {
      this.currentVotes = this.currentVotes.map((item) =>
        (item.option === selectedOption ? { ...item, count: item.count + 1 } : item)
      )
    }
  },
  computed: {
    isVotingEnabled: function() {
      return this.state === 'open';
    },
    votingOptions: function() {
      return this.votes.map(vote => vote.option);
    }
  },
  components: { VoteList, Result }
}
</script>

<style lang="scss">
@import './VotingCard.scss';
</style>
