// tarefa-unidade-1/votacao-angular/src/components/VoteList/VoteList.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'vote-list',
  template: `<div [ngClass]="classes">
    <ul class="vote-list__list">
      <li *ngFor="let option of options" class="vote-list__list-item">
        <simple-button
          (onClick)="onSelectVote(option)"
          [selected]="selectedVote === option"
          [disabled]="disabled"
          [text]="option"
        ></simple-button> 
      </li>
    </ul>
  </div>`,
  styleUrls: ['./VoteList.scss'],
})
export default class VoteListComponent {
  @Input()
  display: String = 'horizontal';

  @Input()
  disabled: Boolean = false;

  @Input()
  options: Array<String> = [];

  @Output()
  onVote = new EventEmitter<String>();

  public selectedVote: String = "";

  public onSelectVote(selectedOption: String): void {
    this.selectedVote = selectedOption;
    this.onVote.emit(selectedOption);
  }

  public get classes(): Object {
    return {
      'vote-list': true,
      'vote-list--horizontal': this.display === 'horizontal',
      'vote-list--vertical': this.display === 'vertical'
    }
  }
}

// tarefa-unidade-1/votacao-vue/src/components/VoteList/VoteList.vue
<template>
  <div :class="{
      'vote-list': true,
      'vote-list--horizontal': display === 'horizontal',
      'vote-list--vertical': display === 'vertical',
    }"
  >
    <ul class="vote-list__list">
      <li v-for="option in options" :key="option" class="vote-list__list-item">
        <simple-button
          :text="option"
          :onClick="onSelectVote(option)"
          :disabled="disabled"
          :selected="selectedVote === option"
        />
      </li>
    </ul>
  </div>
</template>

<script>
import SimpleButton from '../SimpleButton/SimpleButton.vue';

export default {
  props: {
    display: {
      type: String,
      default: 'horizontal',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    options: {
      type: Array,
      default: () => [],
    },
    onVote: {
      type: Function,
      default: () => {},
    },
  },
  data() {
    return {
      selectedVote: null,
    };
  },
  methods: {
    onSelectVote(selectedOption) {
      return () => {
        this.onVote(selectedOption);
      };
    },
  },
  components: { SimpleButton },
};
</script>

<style lang="scss">
@import './VoteList.scss';
</style>
