// tarefa-unidade-1/votacao-svelte/src/components/VoteList/VoteList.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import Button from '../Button/Button.svelte';

  export let display = 'horizontal';
  export let disabled = false;
  export let options = [];

  const dispatch = createEventDispatcher();

  let selectedVote = null;

  function onSelectVote(selectedOption) {
    selectedVote = selectedOption;
    dispatch('vote', selectedOption);
  }
</script>

<style lang="scss">
  @import './VoteList.scss';
</style>

<div
  class="vote-list"
  class:vote-list--horizontal={display === 'horizontal'}
  class:vote-list--vertical={display === 'vertical'}
>
  <ul class="vote-list__list">
    {#each options as option}
      <li class="vote-list__list-item">
        <Button
          on:click={onSelectVote}
          selected={selectedVote === option}
          disabled={disabled}
          text={option}
        />
      </li>
    {/each}
  </ul>
</div>

// tarefa-unidade-1/votacao-vue/src/components/VoteList/VoteList.vue
<template>
  <div :class="{
      'vote-list': true,
      'vote-list--horizontal': display === 'horizontal',
      'vote-list--vertical': display === 'vertical',
    }"
  >
    <ul class="vote-list__list">
      <li v-for="option in options" :key="option" class="vote-list__list-item">
        <simple-button
          :text="option"
          :onClick="onSelectVote(option)"
          :disabled="disabled"
          :selected="selectedVote === option"
        />
      </li>
    </ul>
  </div>
</template>

<script>
import SimpleButton from '../SimpleButton/SimpleButton.vue';

export default {
  props: {
    display: {
      type: String,
      default: 'horizontal',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    options: {
      type: Array,
      default: () => [],
    },
    onVote: {
      type: Function,
      default: () => {},
    },
  },
  data() {
    return {
      selectedVote: null,
    };
  },
  methods: {
    onSelectVote(selectedOption) {
      return () => {
        this.onVote(selectedOption);
      };
    },
  },
  components: { SimpleButton },
};
</script>

<style lang="scss">
@import './VoteList.scss';
</style>
