// tarefa-unidade-1/votacao-svelte/src/components/Result/Result.svelte
<script>
  export let votes = [];

  function calculatePercentage(target, total) {
    return `${((target / total) * 100).toFixed(0)}%`;
  }

  function getTotalVotes() {
    return votes.reduce((acc, { count }) => acc + count, 0);
  }

  function getVotePercentage(votesCount) {
    return calculatePercentage(votesCount, getTotalVotes());
  }

  function getVoteMessage(vote) {
    return `${vote.option} - ${vote.count} votes (${getVotePercentage(vote.count)})`;
  }
</script>

<style lang="scss">
  @import './Result.scss';
</style>

<div class="result">
  <ol class="result__list">
    {#each votes as vote}
      <li class="result__list-item">
        {getVoteMessage(vote)}
      </li>
    {/each}
  </ol>
</div>

// tarefa-unidade-1/votacao-angular/src/components/Result/Result.component.ts
import { Component, Input } from '@angular/core';
import { VoteInterface } from '../sharedInterfaces';

function calculatePercentage(target: number, total: number): String {
  return `${((target / total) * 100).toFixed(0)}%`;
}

@Component({
  selector: 'result',
  template: `<div class="result">
    <ol class="result__list">
      <li *ngFor="let vote of votes" class="result__list-item">
        {{getVoteMessage(vote)}}
      </li>
    </ol>
  </div>`,
  styleUrls: ['./Result.scss'],
})
export default class ResultComponent {
  @Input()
  votes: Array<VoteInterface> = [];

  private get totalVotes(): number {
    return this.votes.reduce((acc, { count }) => acc + count, 0);
  }

  private getVotePercentage(votesCount: number): String {
    return calculatePercentage(votesCount, this.totalVotes);
  }

  public getVoteMessage(vote: VoteInterface): String {
    return `${vote.option} - ${vote.count} votes (${this.getVotePercentage(vote.count)})`;
  }
}
