// tarefa-unidade-2/formulario-vue/src/components/EditableProduct/EditableProduct.vue
<template>
  <div class="editable-product">
    <template v-if="state.isEditing">
      <product-form
        :price="price"
        :imageSrc="imageSrc"
        :title="title"
        :description="description"
        @save="onSave"
      ></product-form>
    </template>
    <template v-else>
      <button @click="state.isEditing = true">
        Click here to edit
      </button>
      <product-details
        :price="price"
        :imageSrc="imageSrc"
        :title="title"
        :description="description"
      ></product-details>
    </template>
    </div>
</template>

<script>
import { reactive } from 'vue';
import ProductDetails from '../ProductDetails/ProductDetails.vue';
import ProductForm from '../ProductForm/ProductForm.vue';
import './EditableProduct.css';

export default {
  name: 'editable-product',
  props: {
    imageSrc: {
      type: String,
      required: false,
      default: ''
    },
    title: {
      type: String,
      required: true,
      default: ''
    },
    description: {
      type: String,
      required: true,
      default: ''
    },
    price: {
      type: Number,
      required: true,
      default: 0
    }
  },
  emits: ['save'],
  components: {
    ProductDetails,
    ProductForm
  },
  setup(props, { emit }) {
    const state = reactive({
      isEditing: false
    })

    return {
      state,
      onSave(formData) {
        state.isEditing = false;
        emit('save', formData);
      }
    }
  }
}
</script>

// tarefa-unidade-2/formulario-angular/src/components/EditableProduct/EditableProduct.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { IProduct } from "../interfaces";

@Component({
  selector: 'editable-product',
  templateUrl: './EditableProduct.html',
  styleUrls: ['./EditableProduct.css']
})
export default class EditableProductComponent {
  @Input()
  price: Number = 0;

  @Input()
  imageSrc: String | undefined;

  @Input()
  title: String = '';

  @Input()
  description: String = '';

  @Output()
  onSave = new EventEmitter<IProduct>();

  public isEditing = false;

  public setIsEditing(isEditing: boolean) {
    this.isEditing = isEditing;
  }

  public onSaveProduct(newData: IProduct) {
    this.setIsEditing(false);
    this.onSave.emit(newData);
  }
};
