// tarefa-unidade-1/votacao-react/src/components/Button/Button.jsx
import PropTypes from 'prop-types';
import classNames from 'classnames';
import './Button.scss';

function Button(props) {
  const {
    onClick, text, selected, disabled,
  } = props;

  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      className={classNames('btn', {
        'btn--selected': (selected && !disabled),
      })}
    >
      {text}
    </button>
  );
}

Button.propTypes = {
  onClick: PropTypes.func,
  text: PropTypes.string,
  selected: PropTypes.bool,
  disabled: PropTypes.bool,
};

Button.defaultProps = {
  onClick: () => {},
  text: '',
  selected: false,
  disabled: false,
};

export default Button;

// tarefa-unidade-1/votacao-svelte/src/components/Button/Button.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let disabled = false;
  export let selected = false;
  export let text = '';

  const dispatch = createEventDispatcher();

  function onClick(event) {
    dispatch('click', event);
  }
</script>

<style lang="scss">
  @import './Button.scss';
</style>

<button
  type="button"
  on:click={onClick}
  class="btn"
  class:btn--selected={(selected && !disabled)}
  {disabled}
>
  {text}
</button>
