// tarefa-unidade-1/votacao-vue/src/components/VotingCard/VotingCard.vue
<template>
  <div class="voting-card">
    <template v-if="isVotingEnabled">
      <h3 class="voting-card__title">{{title}}</h3>
      <div class="voting-card__cabinet">
        <vote-list :options="votingOptions" :onVote="onVote" />
      </div>
    </template>
    <template v-else>
      <result :votes="currentVotes" />
    </template>
  </div>
</template>

<script>
import VoteList from '../VoteList/VoteList.vue';
import Result from '../Result/Result.vue';

export default {
  props: {
    title: {
      type: String,
      default: ''
    },
    state: {
      type: String,
      default: 'open'
    },
    votes: {
      type: Array,
      default: () => []
    }
  },
  data: function() {
    return {
      currentVotes: this.votes
    }
  },
  methods: {
    onVote: function(selectedOption) {
      this.currentVotes = this.currentVotes.map((item) =>
        (item.option === selectedOption ? { ...item, count: item.count + 1 } : item)
      )
    }
  },
  computed: {
    isVotingEnabled: function() {
      return this.state === 'open';
    },
    votingOptions: function() {
      return this.votes.map(vote => vote.option);
    }
  },
  components: { VoteList, Result }
}
</script>

<style lang="scss">
@import './VotingCard.scss';
</style>

// tarefa-unidade-1/votacao-svelte/src/components/VotingCard/VotingCard.svelte
<script>
  import VoteList from '../VoteList/VoteList.svelte';
  import Result from '../Result/Result.svelte';

  export let state = 'open';
  export let title = '';
  export let votes = [];

  let previousVotes = null;

  let currentVotes = null;

  function getVotingOptions() {
    return votes.map(item => item.option);
  }

  function onSelectVote(selectedVote) {
    currentVotes = currentVotes.map(
      (item) => (
        item.option === selectedVote
          ? { ...item, count: item.count + 1 }
          : item
      )
    )
  }

  $: {
    if (previousVotes !== votes) {
      currentVotes = votes;
      previousVotes = votes;
      console.log(votes, currentVotes, previousVotes)
    }
  }
</script>

<style lang="scss">
  @import './VotingCard.scss';
</style>

<div class="voting-card">
  {#if state === 'open'}
    <h3 class="voting-card__title">{title}</h3>
    <div class="voting-card__cabinet">
      <VoteList
        options={getVotingOptions()}
        on:vote={onSelectVote}
      />
    </div>
  {:else if state === 'closed'}
    <Result votes={currentVotes} />
  {/if}
</div>
