// tarefa-unidade-1/votacao-svelte/src/components/Button/Button.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let disabled = false;
  export let selected = false;
  export let text = '';

  const dispatch = createEventDispatcher();

  function onClick(event) {
    dispatch('click', event);
  }
</script>

<style lang="scss">
  @import './Button.scss';
</style>

<button
  type="button"
  on:click={onClick}
  class="btn"
  class:btn--selected={(selected && !disabled)}
  {disabled}
>
  {text}
</button>

// tarefa-unidade-1/votacao-angular/src/components/Button/Button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'simple-button',
  template: `<button
      type="button"
      (click)="onClick.emit($event)"
      [disabled]="disabled"
      [ngClass]="classes"
    >
      {{ text }}
    </button>`,
  styleUrls: ['./Button.scss'],
})
export default class ButtonComponent {
  @Input()
  selected: Boolean = false;

  @Input()
  disabled: Boolean = false;

  @Input()
  text: String = '';

  @Output()
  onClick = new EventEmitter<Event>();

  public get classes(): Object {
    return {
      'btn': true,
      'btn--selected': (this.selected && !this.disabled)
    };
  }
}
