// tarefa-unidade-3/src/components/ProductDetails/ProductDetails.tsx
import {
  Card, CardContent, CardActions, Button, Chip,
} from '@material-ui/core';
import MonetizationOnIcon from '@material-ui/icons/MonetizationOn';
import { formatPrice } from '../common';
import './ProductDetails.scss';

export interface ProductDetailsProps {
  price: string | number;
  title?: string;
  description?: string;
  imageSrc?: string,
  imageLabel?: string,
  onAddToCart?: (event: React.MouseEvent) => void;
}

export default function ProductDetails({ title, description, price, imageSrc, imageLabel, onAddToCart }: ProductDetailsProps) {
  const handleAddToCart = (event: React.MouseEvent) => {
    if (onAddToCart) onAddToCart(event);
  }

  return (
    <Card className="product-details">
      <CardContent>
        <div className="product-details__image-container">
          <Chip className="product-details__price" label={formatPrice(price)} icon={<MonetizationOnIcon />} variant="outlined" color="secondary" />
          {imageSrc ?
            (
              <img src={imageSrc} aria-label={imageLabel} />
            ) : (
              <span className="product-details__no-image-message">No Image</span>
            )
          }
        </div>
        <div className="product-details__title">{title}</div>
        <div className="product-details__description">{description}</div>
      </CardContent>
      <CardActions>
        <Button className="product-details__action-button" variant="outlined" color="primary" onClick={handleAddToCart} disableElevation>Add to Cart</Button>
      </CardActions>
    </Card>
  );
}

ProductDetails.defaultProps = Object.freeze({
  title: '',
  description: '',
  price: 0.00,
});

// tarefa-unidade-2/formulario-vue/src/components/ProductDetails/ProductDetails.vue
<template>
  <div class="product-details">
    <div class="product-details__body">
      <div class="product-details__image-container" >
        <template v-if="!!imageSrc">
          <img
            alt="Product"
            class="product-details__image"
            :src="imageSrc"
          />
        </template>
        <template v-else>
          No image
        </template>
        <span class="product-details__price">
          {{ formattedPrice }}
        </span>
      </div>
      <h3 class="product-details__title">{{ title }}</h3>
      <h4 class="product-details__description">{{ description }}</h4>
    </div>
    <div class="product-details__footer">
      <button>Buy Now</button>
    </div>
  </div>
</template>

<script>
import { computed } from 'vue';
import './ProductDetails.css';

export default {
  name: 'product-details',
  props: [
    'imageSrc',
    'price',
    'title',
    'description'
  ],
  setup(props) {
    return {
      formattedPrice: computed(() => {
        const parsedPrice = parseFloat(props.price.toString());
        return `R$ ${parsedPrice.toFixed(2)}`;
      }),
    }
  }
}
</script>
