// tarefa-unidade-2/formulario-angular/src/components/ProductDetails/ProductDetails.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: 'product-details',
  templateUrl: './ProductDetails.html',
  styleUrls: ['./ProductDetails.css']
})
export default class ProductDetailsComponent {
  @Input()
  price: Number = 0;

  @Input()
  imageSrc: String | undefined;

  @Input()
  title: String = '';

  @Input()
  description: String = '';

  public formatPrice(price: Number) {
    const parsedPrice = parseFloat(price.toString());
    return `R$ ${parsedPrice.toFixed(2)}`;
  }
}

// tarefa-unidade-2/formulario-vue/src/components/ProductDetails/ProductDetails.vue
<template>
  <div class="product-details">
    <div class="product-details__body">
      <div class="product-details__image-container" >
        <template v-if="!!imageSrc">
          <img
            alt="Product"
            class="product-details__image"
            :src="imageSrc"
          />
        </template>
        <template v-else>
          No image
        </template>
        <span class="product-details__price">
          {{ formattedPrice }}
        </span>
      </div>
      <h3 class="product-details__title">{{ title }}</h3>
      <h4 class="product-details__description">{{ description }}</h4>
    </div>
    <div class="product-details__footer">
      <button>Buy Now</button>
    </div>
  </div>
</template>

<script>
import { computed } from 'vue';
import './ProductDetails.css';

export default {
  name: 'product-details',
  props: {
    imageSrc: {
      type: String,
      required: false,
      default: ''
    },
    title: {
      type: String,
      required: true,
      default: ''
    },
    description: {
      type: String,
      required: true,
      default: ''
    },
    price: {
      type: Number,
      required: true,
      default: 0
    }
  },
  setup(props) {
    return {
      formattedPrice: computed(() => {
        const parsedPrice = parseFloat(props.price.toString());
        return `R$ ${parsedPrice.toFixed(2)}`;
      }),
    }
  }
}
</script>
