// tarefa-unidade-2/formulario-react/src/components/EditableProduct/EditableProduct.jsx
import PropTypes from 'prop-types';
import { useState } from 'react';
import './EditableProduct.css';
import ProductDetails from "../ProductDetails/ProductDetails";
import ProductForm from "../ProductForm/ProductForm";

function EditableProduct(props) {
  const [isEditing, setIsEditing] = useState(false);
  const onSave = (data) => {
    setIsEditing(false);
    props.onSave(data);
  };

  return (
    <div className="editable-product">
      {
        isEditing ? (
          <ProductForm {...props} onSave={onSave} />
        ) : (
          <>
            <button onClick={() => setIsEditing(true)}>
              Click here to edit
            </button>
            <ProductDetails {...props} />
          </>
        )
      }
    </div>
  );
}

EditableProduct.propTypes = {
  price: PropTypes.number,
  imageSrc: PropTypes.string,
  title: PropTypes.string,
  description: PropTypes.string,
  onSave: PropTypes.func
}

EditableProduct.defaultProps = {
  price: 0,
  imageSrc: '',
  title: '',
  description: '',
  onSave: () => {}
}

export default EditableProduct;

// tarefa-unidade-2/formulario-vue/src/components/EditableProduct/EditableProduct.vue
<template>
  <div class="editable-product">
    <template v-if="state.isEditing">
      <product-form
        :price="price"
        :imageSrc="imageSrc"
        :title="title"
        :description="description"
        @save="onSave"
      ></product-form>
    </template>
    <template v-else>
      <button @click="state.isEditing = true">
        Click here to edit
      </button>
      <product-details
        :price="price"
        :imageSrc="imageSrc"
        :title="title"
        :description="description"
      ></product-details>
    </template>
    </div>
</template>

<script>
import { reactive } from 'vue';
import ProductDetails from '../ProductDetails/ProductDetails.vue';
import ProductForm from '../ProductForm/ProductForm.vue';
import './EditableProduct.css';

export default {
  name: 'editable-product',
  props: {
    imageSrc: {
      type: String,
      required: false,
      default: ''
    },
    title: {
      type: String,
      required: true,
      default: ''
    },
    description: {
      type: String,
      required: true,
      default: ''
    },
    price: {
      type: Number,
      required: true,
      default: 0
    }
  },
  emits: ['save'],
  components: {
    ProductDetails,
    ProductForm
  },
  setup(props, { emit }) {
    const state = reactive({
      isEditing: false
    })

    return {
      state,
      onSave(formData) {
        state.isEditing = false;
        emit('save', formData);
      }
    }
  }
}
</script>
