// tarefa-unidade-1/votacao-react/src/components/VoteList/VoteList.jsx
import { useState } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import Button from '../Button/Button';
import './VoteList.scss';

function VoteList(props) {
  const {
    options, display, disabled, onVote,
  } = props;

  const [selectedVote, setSelectedVote] = useState(null);

  const onSelectVote = (selectedOption) => () => {
    setSelectedVote(selectedOption);
    onVote(selectedOption);
  };

  return (
    <div className={classNames(
      'vote-list', {
        'vote-list--horizontal': display === 'horizontal',
        'vote-list--vertical': display === 'vertical',
      },
    )}
    >
      <ul className="vote-list__list">
        {options.map((option) => (
          <li key={option} className="vote-list__list-item">
            <Button
              text={option}
              onClick={onSelectVote(option)}
              disabled={disabled}
              selected={selectedVote === option}
            />
          </li>
        ))}
      </ul>
    </div>
  );
}

VoteList.propTypes = {
  disabled: PropTypes.bool,
  display: PropTypes.oneOf(['horizontal', 'vertical']),
  options: PropTypes.arrayOf(PropTypes.string),
  onVote: PropTypes.func,
};

VoteList.defaultProps = {
  disabled: false,
  display: 'horizontal',
  options: [],
  onVote: () => {},
};

export default VoteList;

// tarefa-unidade-1/votacao-svelte/src/components/VoteList/VoteList.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import Button from '../Button/Button.svelte';

  export let display = 'horizontal';
  export let disabled = false;
  export let options = [];

  const dispatch = createEventDispatcher();

  let selectedVote = null;

  function onSelectVote(selectedOption) {
    selectedVote = selectedOption;
    dispatch('vote', selectedOption);
  }
</script>

<style lang="scss">
  @import './VoteList.scss';
</style>

<div
  class="vote-list"
  class:vote-list--horizontal={display === 'horizontal'}
  class:vote-list--vertical={display === 'vertical'}
>
  <ul class="vote-list__list">
    {#each options as option}
      <li class="vote-list__list-item">
        <Button
          on:click={onSelectVote}
          selected={selectedVote === option}
          disabled={disabled}
          text={option}
        />
      </li>
    {/each}
  </ul>
</div>
